//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raxer_2_alpha.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Raxer_2_alpha.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A.
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open.
        /// </summary>
        internal static string abrir {
            get {
                return ResourceManager.GetString("abrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open application (.exe).
        /// </summary>
        internal static string abrirAplicacion {
            get {
                return ResourceManager.GetString("abrirAplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open file.
        /// </summary>
        internal static string abrirArchivo {
            get {
                return ResourceManager.GetString("abrirArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open folder.
        /// </summary>
        internal static string abrirFolder {
            get {
                return ResourceManager.GetString("abrirFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open website.
        /// </summary>
        internal static string abrirSitioWeb {
            get {
                return ResourceManager.GetString("abrirSitioWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actions.
        /// </summary>
        internal static string accion {
            get {
                return ResourceManager.GetString("accion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add (+).
        /// </summary>
        internal static string ADD {
            get {
                return ResourceManager.GetString("ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forward (side).
        /// </summary>
        internal static string adelante {
            get {
                return ResourceManager.GetString("adelante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Alt.
        /// </summary>
        internal static string ALT_L {
            get {
                return ResourceManager.GetString("ALT_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Alt.
        /// </summary>
        internal static string ALT_R {
            get {
                return ResourceManager.GetString("ALT_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Applications.
        /// </summary>
        internal static string APPS {
            get {
                return ResourceManager.GetString("APPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Backward (side).
        /// </summary>
        internal static string atras {
            get {
                return ResourceManager.GetString("atras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attn.
        /// </summary>
        internal static string ATTN {
            get {
                return ResourceManager.GetString("ATTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a B.
        /// </summary>
        internal static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Backspace.
        /// </summary>
        internal static string BACK {
            get {
                return ResourceManager.GetString("BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volume down.
        /// </summary>
        internal static string bajarVolumen {
            get {
                return ResourceManager.GetString("bajarVolumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decrease microphone volume.
        /// </summary>
        internal static string bajarVolumenMicrofono {
            get {
                return ResourceManager.GetString("bajarVolumenMicrofono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse button.
        /// </summary>
        internal static string botonMouse {
            get {
                return ResourceManager.GetString("botonMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browser Back.
        /// </summary>
        internal static string BROWSER_BACK {
            get {
                return ResourceManager.GetString("BROWSER_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browser Favorites.
        /// </summary>
        internal static string BROWSER_FAVORITES {
            get {
                return ResourceManager.GetString("BROWSER_FAVORITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browser Foward.
        /// </summary>
        internal static string BROWSER_FORWARD {
            get {
                return ResourceManager.GetString("BROWSER_FORWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browser Home.
        /// </summary>
        internal static string BROWSER_HOME {
            get {
                return ResourceManager.GetString("BROWSER_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browser Refersh.
        /// </summary>
        internal static string BROWSER_REFRESH {
            get {
                return ResourceManager.GetString("BROWSER_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browser Search.
        /// </summary>
        internal static string BROWSER_SEARCH {
            get {
                return ResourceManager.GetString("BROWSER_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browser Stop.
        /// </summary>
        internal static string BROWSER_STOP {
            get {
                return ResourceManager.GetString("BROWSER_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string buscar {
            get {
                return ResourceManager.GetString("buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string busquedaAsk {
            get {
                return ResourceManager.GetString("busquedaAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string busquedaBing {
            get {
                return ResourceManager.GetString("busquedaBing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string busquedaDuckduckgo {
            get {
                return ResourceManager.GetString("busquedaDuckduckgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string busquedaGoogle {
            get {
                return ResourceManager.GetString("busquedaGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string busquedaWikipedia {
            get {
                return ResourceManager.GetString("busquedaWikipedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string busquedaYahoo {
            get {
                return ResourceManager.GetString("busquedaYahoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string busquedaYoutube {
            get {
                return ResourceManager.GetString("busquedaYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C.
        /// </summary>
        internal static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control break processing.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caps lock.
        /// </summary>
        internal static string CAPITAL {
            get {
                return ResourceManager.GetString("CAPITAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close window.
        /// </summary>
        internal static string cerrarVentana {
            get {
                return ResourceManager.GetString("cerrarVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change mouse pointer speed.
        /// </summary>
        internal static string changuePunteroSpeed {
            get {
                return ResourceManager.GetString("changuePunteroSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        internal static string CLEAR {
            get {
                return ResourceManager.GetString("CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scroll wheel click.
        /// </summary>
        internal static string clicCentral {
            get {
                return ResourceManager.GetString("clicCentral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right click.
        /// </summary>
        internal static string clicDerecho {
            get {
                return ResourceManager.GetString("clicDerecho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left click.
        /// </summary>
        internal static string clicIzquierdo {
            get {
                return ResourceManager.GetString("clicIzquierdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Key combination.
        /// </summary>
        internal static string comboTeclas {
            get {
                return ResourceManager.GetString("comboTeclas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string COMBOTECLAS___SEPARATOR {
            get {
                return ResourceManager.GetString("COMBOTECLAS - SEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control.
        /// </summary>
        internal static string CONTROL {
            get {
                return ResourceManager.GetString("CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Control.
        /// </summary>
        internal static string CONTROL_L {
            get {
                return ResourceManager.GetString("CONTROL_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Control.
        /// </summary>
        internal static string CONTROL_R {
            get {
                return ResourceManager.GetString("CONTROL_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy.
        /// </summary>
        internal static string copiar {
            get {
                return ResourceManager.GetString("copiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cut.
        /// </summary>
        internal static string cortar {
            get {
                return ResourceManager.GetString("cortar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crsel.
        /// </summary>
        internal static string CRSEL {
            get {
                return ResourceManager.GetString("CRSEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a D.
        /// </summary>
        internal static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decimal (.).
        /// </summary>
        internal static string DECIMAL {
            get {
                return ResourceManager.GetString("DECIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disabled.
        /// </summary>
        internal static string deshabilitar {
            get {
                return ResourceManager.GetString("deshabilitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disabled.
        /// </summary>
        internal static string deshabilitarBoton {
            get {
                return ResourceManager.GetString("deshabilitarBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Undo.
        /// </summary>
        internal static string deshacer {
            get {
                return ResourceManager.GetString("deshacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divide (/).
        /// </summary>
        internal static string DIVIDE {
            get {
                return ResourceManager.GetString("DIVIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Down arrow.
        /// </summary>
        internal static string DOWN {
            get {
                return ResourceManager.GetString("DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E.
        /// </summary>
        internal static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit commands.
        /// </summary>
        internal static string edicion {
            get {
                return ResourceManager.GetString("edicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End.
        /// </summary>
        internal static string END {
            get {
                return ResourceManager.GetString("END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Erase EOF.
        /// </summary>
        internal static string EREOF {
            get {
                return ResourceManager.GetString("EREOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escape.
        /// </summary>
        internal static string ESCAPE {
            get {
                return ResourceManager.GetString("ESCAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Execute.
        /// </summary>
        internal static string EXECUTE {
            get {
                return ResourceManager.GetString("EXECUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Experimental.
        /// </summary>
        internal static string experimental {
            get {
                return ResourceManager.GetString("experimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exsel.
        /// </summary>
        internal static string EXSEL {
            get {
                return ResourceManager.GetString("EXSEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F.
        /// </summary>
        internal static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F1.
        /// </summary>
        internal static string F1 {
            get {
                return ResourceManager.GetString("F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F10.
        /// </summary>
        internal static string F10 {
            get {
                return ResourceManager.GetString("F10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F11.
        /// </summary>
        internal static string F11 {
            get {
                return ResourceManager.GetString("F11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F12.
        /// </summary>
        internal static string F12 {
            get {
                return ResourceManager.GetString("F12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F13.
        /// </summary>
        internal static string F13 {
            get {
                return ResourceManager.GetString("F13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F14.
        /// </summary>
        internal static string F14 {
            get {
                return ResourceManager.GetString("F14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F15.
        /// </summary>
        internal static string F15 {
            get {
                return ResourceManager.GetString("F15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F16.
        /// </summary>
        internal static string F16 {
            get {
                return ResourceManager.GetString("F16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F17.
        /// </summary>
        internal static string F17 {
            get {
                return ResourceManager.GetString("F17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F18.
        /// </summary>
        internal static string F18 {
            get {
                return ResourceManager.GetString("F18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F19.
        /// </summary>
        internal static string F19 {
            get {
                return ResourceManager.GetString("F19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F2.
        /// </summary>
        internal static string F2 {
            get {
                return ResourceManager.GetString("F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F20.
        /// </summary>
        internal static string F20 {
            get {
                return ResourceManager.GetString("F20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F21.
        /// </summary>
        internal static string F21 {
            get {
                return ResourceManager.GetString("F21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F22.
        /// </summary>
        internal static string F22 {
            get {
                return ResourceManager.GetString("F22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F23.
        /// </summary>
        internal static string F23 {
            get {
                return ResourceManager.GetString("F23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F24.
        /// </summary>
        internal static string F24 {
            get {
                return ResourceManager.GetString("F24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F3.
        /// </summary>
        internal static string F3 {
            get {
                return ResourceManager.GetString("F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F4.
        /// </summary>
        internal static string F4 {
            get {
                return ResourceManager.GetString("F4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F5.
        /// </summary>
        internal static string F5 {
            get {
                return ResourceManager.GetString("F5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F6.
        /// </summary>
        internal static string F6 {
            get {
                return ResourceManager.GetString("F6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F7.
        /// </summary>
        internal static string F7 {
            get {
                return ResourceManager.GetString("F7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F8.
        /// </summary>
        internal static string F8 {
            get {
                return ResourceManager.GetString("F8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F9.
        /// </summary>
        internal static string F9 {
            get {
                return ResourceManager.GetString("F9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lock on the X-axis.
        /// </summary>
        internal static string fijarHorizontal {
            get {
                return ResourceManager.GetString("fijarHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lock on the Y-axis.
        /// </summary>
        internal static string fijarVertical {
            get {
                return ResourceManager.GetString("fijarVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IME Final mode.
        /// </summary>
        internal static string FINALMODE {
            get {
                return ResourceManager.GetString("FINALMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a G.
        /// </summary>
        internal static string G {
            get {
                return ResourceManager.GetString("G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string guardar {
            get {
                return ResourceManager.GetString("guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a H.
        /// </summary>
        internal static string H {
            get {
                return ResourceManager.GetString("H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IME Hangul mode.
        /// </summary>
        internal static string HANGULMODE {
            get {
                return ResourceManager.GetString("HANGULMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IME Hanja mode.
        /// </summary>
        internal static string HANJAMODE {
            get {
                return ResourceManager.GetString("HANJAMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        internal static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        internal static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I.
        /// </summary>
        internal static string I {
            get {
                return ResourceManager.GetString("I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IME Accept.
        /// </summary>
        internal static string IMEACCEPT {
            get {
                return ResourceManager.GetString("IMEACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IME Convert.
        /// </summary>
        internal static string IMECONVERT {
            get {
                return ResourceManager.GetString("IMECONVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IME Mode Change Request.
        /// </summary>
        internal static string IMEMODECHANGE {
            get {
                return ResourceManager.GetString("IMEMODECHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IME Nonconvert.
        /// </summary>
        internal static string IMENONCONVERT {
            get {
                return ResourceManager.GetString("IMENONCONVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Print.
        /// </summary>
        internal static string imprimir {
            get {
                return ResourceManager.GetString("imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disable.
        /// </summary>
        internal static string inhabilitar {
            get {
                return ResourceManager.GetString("inhabilitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert.
        /// </summary>
        internal static string INSERT {
            get {
                return ResourceManager.GetString("INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a J.
        /// </summary>
        internal static string J {
            get {
                return ResourceManager.GetString("J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IME Junja mode.
        /// </summary>
        internal static string JUNJAMODE {
            get {
                return ResourceManager.GetString("JUNJAMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a K.
        /// </summary>
        internal static string K {
            get {
                return ResourceManager.GetString("K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IME Kana mode.
        /// </summary>
        internal static string KANAMODE {
            get {
                return ResourceManager.GetString("KANAMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IME Kanji mode.
        /// </summary>
        internal static string KANJIMODE {
            get {
                return ResourceManager.GetString("KANJIMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kill app⚠️.
        /// </summary>
        internal static string kill {
            get {
                return ResourceManager.GetString("kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a L.
        /// </summary>
        internal static string L {
            get {
                return ResourceManager.GetString("L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Launch app 1.
        /// </summary>
        internal static string LAUNCH_APP1 {
            get {
                return ResourceManager.GetString("LAUNCH_APP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Launch app 2.
        /// </summary>
        internal static string LAUNCH_APP2 {
            get {
                return ResourceManager.GetString("LAUNCH_APP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Mail.
        /// </summary>
        internal static string LAUNCH_MAIL {
            get {
                return ResourceManager.GetString("LAUNCH_MAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select media.
        /// </summary>
        internal static string LAUNCH_MEDIA_SELECT {
            get {
                return ResourceManager.GetString("LAUNCH_MEDIA_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left arrow.
        /// </summary>
        internal static string LEFT {
            get {
                return ResourceManager.GetString("LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a M.
        /// </summary>
        internal static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximize window.
        /// </summary>
        internal static string maximizarVentana {
            get {
                return ResourceManager.GetString("maximizarVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next track.
        /// </summary>
        internal static string MEDIA_NEXT_TRACK {
            get {
                return ResourceManager.GetString("MEDIA_NEXT_TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play/Pause media.
        /// </summary>
        internal static string MEDIA_PLAY_PAUSE {
            get {
                return ResourceManager.GetString("MEDIA_PLAY_PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previous track.
        /// </summary>
        internal static string MEDIA_PREV_TRACK {
            get {
                return ResourceManager.GetString("MEDIA_PREV_TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stop media.
        /// </summary>
        internal static string MEDIA_STOP {
            get {
                return ResourceManager.GetString("MEDIA_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alt.
        /// </summary>
        internal static string MENU {
            get {
                return ResourceManager.GetString("MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decrease microphone volume.
        /// </summary>
        internal static string micBajarVol {
            get {
                return ResourceManager.GetString("micBajarVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Increase microphone volume.
        /// </summary>
        internal static string micSubirVol {
            get {
                return ResourceManager.GetString("micSubirVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimize all.
        /// </summary>
        internal static string minimizarTodo {
            get {
                return ResourceManager.GetString("minimizarTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimize window.
        /// </summary>
        internal static string minimizarVentana {
            get {
                return ResourceManager.GetString("minimizarVentana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Media controls.
        /// </summary>
        internal static string multimedia {
            get {
                return ResourceManager.GetString("multimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiply (*).
        /// </summary>
        internal static string MULTIPLY {
            get {
                return ResourceManager.GetString("MULTIPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mute.
        /// </summary>
        internal static string mute {
            get {
                return ResourceManager.GetString("mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N.
        /// </summary>
        internal static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Page down.
        /// </summary>
        internal static string NEXT {
            get {
                return ResourceManager.GetString("NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        internal static string nuevo {
            get {
                return ResourceManager.GetString("nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        internal static string NUM_0 {
            get {
                return ResourceManager.GetString("NUM_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        internal static string NUM_1 {
            get {
                return ResourceManager.GetString("NUM_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2.
        /// </summary>
        internal static string NUM_2 {
            get {
                return ResourceManager.GetString("NUM_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3.
        /// </summary>
        internal static string NUM_3 {
            get {
                return ResourceManager.GetString("NUM_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4.
        /// </summary>
        internal static string NUM_4 {
            get {
                return ResourceManager.GetString("NUM_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5.
        /// </summary>
        internal static string NUM_5 {
            get {
                return ResourceManager.GetString("NUM_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 6.
        /// </summary>
        internal static string NUM_6 {
            get {
                return ResourceManager.GetString("NUM_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 7.
        /// </summary>
        internal static string NUM_7 {
            get {
                return ResourceManager.GetString("NUM_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 8.
        /// </summary>
        internal static string NUM_8 {
            get {
                return ResourceManager.GetString("NUM_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 9.
        /// </summary>
        internal static string NUM_9 {
            get {
                return ResourceManager.GetString("NUM_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Num Lock.
        /// </summary>
        internal static string NUMLOCK {
            get {
                return ResourceManager.GetString("NUMLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numpad 0.
        /// </summary>
        internal static string NUMPAD_0 {
            get {
                return ResourceManager.GetString("NUMPAD_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numpad 1.
        /// </summary>
        internal static string NUMPAD_1 {
            get {
                return ResourceManager.GetString("NUMPAD_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numpad 2.
        /// </summary>
        internal static string NUMPAD_2 {
            get {
                return ResourceManager.GetString("NUMPAD_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numpad 3.
        /// </summary>
        internal static string NUMPAD_3 {
            get {
                return ResourceManager.GetString("NUMPAD_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numpad 4.
        /// </summary>
        internal static string NUMPAD_4 {
            get {
                return ResourceManager.GetString("NUMPAD_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numpad 5.
        /// </summary>
        internal static string NUMPAD_5 {
            get {
                return ResourceManager.GetString("NUMPAD_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numpad 6.
        /// </summary>
        internal static string NUMPAD_6 {
            get {
                return ResourceManager.GetString("NUMPAD_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numpad 7.
        /// </summary>
        internal static string NUMPAD_7 {
            get {
                return ResourceManager.GetString("NUMPAD_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numpad 8.
        /// </summary>
        internal static string NUMPAD_8 {
            get {
                return ResourceManager.GetString("NUMPAD_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numpad 9.
        /// </summary>
        internal static string NUMPAD_9 {
            get {
                return ResourceManager.GetString("NUMPAD_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a O.
        /// </summary>
        internal static string O {
            get {
                return ResourceManager.GetString("O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oem1.
        /// </summary>
        internal static string OEM_1 {
            get {
                return ResourceManager.GetString("OEM_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oem102.
        /// </summary>
        internal static string OEM_102 {
            get {
                return ResourceManager.GetString("OEM_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oem2.
        /// </summary>
        internal static string OEM_2 {
            get {
                return ResourceManager.GetString("OEM_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oem3.
        /// </summary>
        internal static string OEM_3 {
            get {
                return ResourceManager.GetString("OEM_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oem4.
        /// </summary>
        internal static string OEM_4 {
            get {
                return ResourceManager.GetString("OEM_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oem5.
        /// </summary>
        internal static string OEM_5 {
            get {
                return ResourceManager.GetString("OEM_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oem6.
        /// </summary>
        internal static string OEM_6 {
            get {
                return ResourceManager.GetString("OEM_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oem7.
        /// </summary>
        internal static string OEM_7 {
            get {
                return ResourceManager.GetString("OEM_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oem8.
        /// </summary>
        internal static string OEM_8 {
            get {
                return ResourceManager.GetString("OEM_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oemclear.
        /// </summary>
        internal static string OEM_CLEAR {
            get {
                return ResourceManager.GetString("OEM_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oemcomma.
        /// </summary>
        internal static string OEM_COMMA {
            get {
                return ResourceManager.GetString("OEM_COMMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oemminus.
        /// </summary>
        internal static string OEM_MINUS {
            get {
                return ResourceManager.GetString("OEM_MINUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oemperiod.
        /// </summary>
        internal static string OEM_PERIOD {
            get {
                return ResourceManager.GetString("OEM_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oemplus.
        /// </summary>
        internal static string OEM_PLUS {
            get {
                return ResourceManager.GetString("OEM_PLUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P.
        /// </summary>
        internal static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pa1.
        /// </summary>
        internal static string PA1 {
            get {
                return ResourceManager.GetString("PA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pause.
        /// </summary>
        internal static string PAUSE {
            get {
                return ResourceManager.GetString("PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste.
        /// </summary>
        internal static string pegar {
            get {
                return ResourceManager.GetString("pegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previous track.
        /// </summary>
        internal static string pistaAnterior {
            get {
                return ResourceManager.GetString("pistaAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next track.
        /// </summary>
        internal static string pistaSiguiente {
            get {
                return ResourceManager.GetString("pistaSiguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play.
        /// </summary>
        internal static string PLAY {
            get {
                return ResourceManager.GetString("PLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play/Pause.
        /// </summary>
        internal static string playPause {
            get {
                return ResourceManager.GetString("playPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default.
        /// </summary>
        internal static string porDefecto {
            get {
                return ResourceManager.GetString("porDefecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Print.
        /// </summary>
        internal static string PRINT {
            get {
                return ResourceManager.GetString("PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Page up.
        /// </summary>
        internal static string PRIOR {
            get {
                return ResourceManager.GetString("PRIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IME Process.
        /// </summary>
        internal static string PROCESSKEY {
            get {
                return ResourceManager.GetString("PROCESSKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse pointer.
        /// </summary>
        internal static string puntero {
            get {
                return ResourceManager.GetString("puntero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Q.
        /// </summary>
        internal static string Q {
            get {
                return ResourceManager.GetString("Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a R.
        /// </summary>
        internal static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redo.
        /// </summary>
        internal static string rehacer {
            get {
                return ResourceManager.GetString("rehacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter.
        /// </summary>
        internal static string RETURN {
            get {
                return ResourceManager.GetString("RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right arrow.
        /// </summary>
        internal static string RIGHT {
            get {
                return ResourceManager.GetString("RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a S.
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scroll Lock.
        /// </summary>
        internal static string SCROLL {
            get {
                return ResourceManager.GetString("SCROLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scroll down.
        /// </summary>
        internal static string scrollDown {
            get {
                return ResourceManager.GetString("scrollDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scroll left.
        /// </summary>
        internal static string scrollLeft {
            get {
                return ResourceManager.GetString("scrollLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scroll right.
        /// </summary>
        internal static string scrollRight {
            get {
                return ResourceManager.GetString("scrollRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scroll up.
        /// </summary>
        internal static string scrollUp {
            get {
                return ResourceManager.GetString("scrollUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose a key combination.
        /// </summary>
        internal static string seleccionarCombo {
            get {
                return ResourceManager.GetString("seleccionarCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select all.
        /// </summary>
        internal static string seleccionarTodo {
            get {
                return ResourceManager.GetString("seleccionarTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select.
        /// </summary>
        internal static string SELECT {
            get {
                return ResourceManager.GetString("SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Separator.
        /// </summary>
        internal static string SEPARATOR {
            get {
                return ResourceManager.GetString("SEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string SEPARATOR___ABRIR {
            get {
                return ResourceManager.GetString("SEPARATOR - ABRIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string SEPARATOR___ACCIONES {
            get {
                return ResourceManager.GetString("SEPARATOR - ACCIONES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string SEPARATOR___ACCIONES_2 {
            get {
                return ResourceManager.GetString("SEPARATOR - ACCIONES 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string SEPARATOR___EDICION {
            get {
                return ResourceManager.GetString("SEPARATOR - EDICION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string SEPARATOR___INHABILITAR {
            get {
                return ResourceManager.GetString("SEPARATOR - INHABILITAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string SEPARATOR___MOUSEBOTON {
            get {
                return ResourceManager.GetString("SEPARATOR - MOUSEBOTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string SEPARATOR___MULTIMEDIA {
            get {
                return ResourceManager.GetString("SEPARATOR - MULTIMEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string SEPARATOR___PUNTERO {
            get {
                return ResourceManager.GetString("SEPARATOR - PUNTERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string SEPARATOR_TECLAS_VIRTUALES {
            get {
                return ResourceManager.GetString("SEPARATOR TECLAS VIRTUALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string SEPARATOR_TIPOS_DE_REASIGNACION {
            get {
                return ResourceManager.GetString("SEPARATOR TIPOS DE REASIGNACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set mouse pointer speed.
        /// </summary>
        internal static string setPunteroSpeed {
            get {
                return ResourceManager.GetString("setPunteroSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shift.
        /// </summary>
        internal static string SHIFT {
            get {
                return ResourceManager.GetString("SHIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Shift.
        /// </summary>
        internal static string SHIFT_L {
            get {
                return ResourceManager.GetString("SHIFT_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Shift.
        /// </summary>
        internal static string SHIFT_R {
            get {
                return ResourceManager.GetString("SHIFT_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mute.
        /// </summary>
        internal static string silenciar {
            get {
                return ResourceManager.GetString("silenciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sleep.
        /// </summary>
        internal static string SLEEP {
            get {
                return ResourceManager.GetString("SLEEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Print screen.
        /// </summary>
        internal static string SNAPSHOT {
            get {
                return ResourceManager.GetString("SNAPSHOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Space.
        /// </summary>
        internal static string SPACE {
            get {
                return ResourceManager.GetString("SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stop.
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volume up.
        /// </summary>
        internal static string subirVolumen {
            get {
                return ResourceManager.GetString("subirVolumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Increase microphone volume.
        /// </summary>
        internal static string subirVolumenMicrofono {
            get {
                return ResourceManager.GetString("subirVolumenMicrofono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Substract (-).
        /// </summary>
        internal static string SUBTRACT {
            get {
                return ResourceManager.GetString("SUBTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle maximize.
        /// </summary>
        internal static string switchMaximizar {
            get {
                return ResourceManager.GetString("switchMaximizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Microphone on/off .
        /// </summary>
        internal static string switchMic {
            get {
                return ResourceManager.GetString("switchMic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle minimize.
        /// </summary>
        internal static string switchMinimizar {
            get {
                return ResourceManager.GetString("switchMinimizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T.
        /// </summary>
        internal static string T {
            get {
                return ResourceManager.GetString("T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tab.
        /// </summary>
        internal static string TAB {
            get {
                return ResourceManager.GetString("TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Key.
        /// </summary>
        internal static string tecla {
            get {
                return ResourceManager.GetString("tecla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a U.
        /// </summary>
        internal static string U {
            get {
                return ResourceManager.GetString("U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Up arrow.
        /// </summary>
        internal static string UP {
            get {
                return ResourceManager.GetString("UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a V.
        /// </summary>
        internal static string V {
            get {
                return ResourceManager.GetString("V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volume Down.
        /// </summary>
        internal static string VOLUME_DOWN {
            get {
                return ResourceManager.GetString("VOLUME_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volume Mute.
        /// </summary>
        internal static string VOLUME_MUTE {
            get {
                return ResourceManager.GetString("VOLUME_MUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volume Up.
        /// </summary>
        internal static string VOLUME_UP {
            get {
                return ResourceManager.GetString("VOLUME_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a W.
        /// </summary>
        internal static string W {
            get {
                return ResourceManager.GetString("W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wild drag.
        /// </summary>
        internal static string wildDrag {
            get {
                return ResourceManager.GetString("wildDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left Windows.
        /// </summary>
        internal static string WIN_L {
            get {
                return ResourceManager.GetString("WIN_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Windows.
        /// </summary>
        internal static string WIN_R {
            get {
                return ResourceManager.GetString("WIN_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a X.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Y.
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Z.
        /// </summary>
        internal static string Z {
            get {
                return ResourceManager.GetString("Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zoom.
        /// </summary>
        internal static string ZOOM {
            get {
                return ResourceManager.GetString("ZOOM", resourceCulture);
            }
        }
    }
}
