//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raxer.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Raxer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a some-abcd.
        /// </summary>
        public static string abcd {
            get {
                return ResourceManager.GetString("abcd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Raxer.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string btn_cancel {
            get {
                return ResourceManager.GetString("btn-cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        public static string btn_ok {
            get {
                return ResourceManager.GetString("btn-ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activate hold.
        /// </summary>
        public static string check_activate_hold {
            get {
                return ResourceManager.GetString("check-activate-hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string menu_exit {
            get {
                return ResourceManager.GetString("menu-exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open settings.
        /// </summary>
        public static string menu_open_settings {
            get {
                return ResourceManager.GetString("menu-open-settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start with system.
        /// </summary>
        public static string menu_start_with_system {
            get {
                return ResourceManager.GetString("menu-start-with-system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string nav_about {
            get {
                return ResourceManager.GetString("nav-about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filters.
        /// </summary>
        public static string nav_filters {
            get {
                return ResourceManager.GetString("nav-filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profiles.
        /// </summary>
        public static string nav_profiles {
            get {
                return ResourceManager.GetString("nav-profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        public static string nav_start {
            get {
                return ResourceManager.GetString("nav-start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string page_title_about {
            get {
                return ResourceManager.GetString("page-title-about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a App filter.
        /// </summary>
        public static string page_title_filters {
            get {
                return ResourceManager.GetString("page-title-filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profiles.
        /// </summary>
        public static string page_title_profiles {
            get {
                return ResourceManager.GetString("page-title-profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        public static string page_title_start {
            get {
                return ResourceManager.GetString("page-title-start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Appearance.
        /// </summary>
        public static string section_appearance {
            get {
                return ResourceManager.GetString("section-appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Double click speed.
        /// </summary>
        public static string section_dblclick_speed {
            get {
                return ResourceManager.GetString("section-dblclick-speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hold &amp; Drag.
        /// </summary>
        public static string section_hold {
            get {
                return ResourceManager.GetString("section-hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movement.
        /// </summary>
        public static string section_movement {
            get {
                return ResourceManager.GetString("section-movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visibility.
        /// </summary>
        public static string section_visibility {
            get {
                return ResourceManager.GetString("section-visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wheel.
        /// </summary>
        public static string section_wheel {
            get {
                return ResourceManager.GetString("section-wheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Raxer - Settings.
        /// </summary>
        public static string settings_title {
            get {
                return ResourceManager.GetString("settings-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start with Windows.
        /// </summary>
        public static string start_with_windows {
            get {
                return ResourceManager.GetString("start-with-windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remap de mouse.
        /// </summary>
        public static string tagline {
            get {
                return ResourceManager.GetString("tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horizontal.
        /// </summary>
        public static string wheel_horizontal {
            get {
                return ResourceManager.GetString("wheel-horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Whole page per scroll.
        /// </summary>
        public static string wheel_page_per_scroll {
            get {
                return ResourceManager.GetString("wheel-page-per-scroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vertical.
        /// </summary>
        public static string wheel_vertical {
            get {
                return ResourceManager.GetString("wheel-vertical", resourceCulture);
            }
        }
    }
}
